/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ServiceCategory = IDL.Variant({
  'plumber' : IDL.Null,
  'electrician' : IDL.Null,
  'painter' : IDL.Null,
  'pestControl' : IDL.Null,
  'acRepair' : IDL.Null,
  'carpenter' : IDL.Null,
  'applianceRepair' : IDL.Null,
});
export const Expert = IDL.Record({
  'bio' : IDL.Text,
  'yearsOfExperience' : IDL.Nat,
  'serviceCategory' : ServiceCategory,
  'owner' : IDL.Principal,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrUpdateProfile' : IDL.Func(
      [IDL.Text, IDL.Text, ServiceCategory, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'deleteOwnProfile' : IDL.Func([], [], []),
  'getAllExperts' : IDL.Func([], [IDL.Vec(Expert)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExpert' : IDL.Func([IDL.Principal], [IDL.Opt(Expert)], ['query']),
  'getExpertsByCategory' : IDL.Func(
      [ServiceCategory],
      [IDL.Vec(Expert)],
      ['query'],
    ),
  'getOwnProfile' : IDL.Func([], [Expert], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ServiceCategory = IDL.Variant({
    'plumber' : IDL.Null,
    'electrician' : IDL.Null,
    'painter' : IDL.Null,
    'pestControl' : IDL.Null,
    'acRepair' : IDL.Null,
    'carpenter' : IDL.Null,
    'applianceRepair' : IDL.Null,
  });
  const Expert = IDL.Record({
    'bio' : IDL.Text,
    'yearsOfExperience' : IDL.Nat,
    'serviceCategory' : ServiceCategory,
    'owner' : IDL.Principal,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrUpdateProfile' : IDL.Func(
        [IDL.Text, IDL.Text, ServiceCategory, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'deleteOwnProfile' : IDL.Func([], [], []),
    'getAllExperts' : IDL.Func([], [IDL.Vec(Expert)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExpert' : IDL.Func([IDL.Principal], [IDL.Opt(Expert)], ['query']),
    'getExpertsByCategory' : IDL.Func(
        [ServiceCategory],
        [IDL.Vec(Expert)],
        ['query'],
      ),
    'getOwnProfile' : IDL.Func([], [Expert], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };